-- vim.pack.add {
--   'https://github.com/rachartier/tiny-inline-diagnostic.nvim',
-- }
-- require('tiny-inline-diagnostic').setup {
--   vim.diagnostic.config { virtual_text = false }, -- Disable Neovim's default virtual text diagnostics
--   vim.keymap.set('n', '<leader>De', '<cmd>TinyInlineDiag enable<cr>', { desc = 'Enable diagnostics' }),
--   vim.keymap.set('n', '<leader>Dd', '<cmd>TinyInlineDiag disable<cr>', { desc = 'Disable diagnostics' }),
--   vim.keymap.set('n', '<leader>Dt', '<cmd>TinyInlineDiag toggle<cr>', { desc = 'Toggle diagnostics' }),
-- }
